name: azure-cli
version: "0.10.3-trunk"
summary: Microsoft Azure Cross Platform Command Line
description: a cross-platform command line interface for developers and IT
 administrators to develop, deploy and manage Microsoft Azure applications.
confinement: strict

apps:
  azure-cli:
    command: azure-cli
    plugs: [network]

parts:
  azure-xplat-cli:
    plugin: nodejs
    source: .
  launcher:
    plugin: dump
    source: snap-extra/
